src/Entity/Ad.php
<?php

namespace App\Entity;

use App\Entity\User;
use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Vich\UploaderBundle\Mapping\Annotation as Vich;


/**
 * @ORM\Entity(repositoryClass="App\Repository\AdRepository")
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(fields={"title"}, message="ce titre est déjà utilisé par une autre annonce, merci de le modifier")
 * @Vich\Uploadable
 */
class Ad
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min = 10, max = 255, minMessage = "Votre titre doit faire au moins 10 caractères")
     */
    private $title;


    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min = 20, minMessage = "Votre introduction doit faire au moins 20 caractères")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min = 100, minMessage = "Votre description doit faire au moins 100 caractères")
     */
    private $content;

    /**
     * @var File|null
     * @Vich\UploadableField(mapping="upload_image", fileNameProperty="filename")
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string")
     * @var string|null
     */
    private $filename;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="ads")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="ad", orphanRemoval=true)
     */
    private $comments;

    /**
     * @ORM\Column(type="datetime")
     */
    private $update_at;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    /**
     * hasLifecycleCallbaks action
     *
     * @ORM\PrePersist
     * @ORM\PreUpdate
     *
     */
    public function perPersist()
    {
        if (empty($this->createdAt)) {
            $this->createdAt = new \DateTime();
        }
    }

    /**
     * @ORM\PrePersist
     */
    public function setupdateAtValue()
    {
        $this->updatedAt = new \DateTime();
    }

    /**
     * permet d'initialiser un slug!
     * 
     * @ORM\PrePersist
     * @ORM\PreUpdate
     *
     * @return void
     */
    public function initialiazeSlug(){
        if(empty($this->slug)){
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->title);
        }

    }


    /**
     * permet de recuperer le commentaire d'un author/user par rapport à une annonce
     *
     * @param User $author
     * @return Comment|null
     */
    public function getCommentFromAuthor(User $author){
        foreach($this->comments as $comment){
            if($comment->getAuthor() === $author) return $comment;
        }
        return null;
    }


    /**
     * permet d'obtenir la moyenne des notes d'une annonce
     *
     * @return float
     */
    public function getAvgRatings(){
        //calculer la somme des notations
        $sum = array_reduce($this->comments->toArray(), function($total, $comment){
            return $total + $comment->getRating();
        }, 0);

        // Faire la moyenne

        if(count($this->comments) > 0) return $sum / count($this->comments);
        return 0 ;

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    /**
     * @return mixed
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * @param mixed $createdAt
     * @return Ad
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;
        return $this;
    }



    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return File
     */
    public function getImageFile()
    {
        return $this->imageFile;
    }

    /**
     * @param File $imageFile
     * @return Ad
     */
    public function setImageFile($imageFile)
    {
        $this->imageFile = $imageFile;
        if ($this->imageFile instanceof UploadedFile){
            $this->update_at = new \DateTime('now');
            return $this;
        }
    }

    /**
     * @return mixed
     */
    public function getFilename()
    {
        return $this->filename;
    }

    /**
     * @param mixed $filename
     * @return Ad
     */
    public function setFilename($filename)
    {
        $this->filename = $filename;
        return $this;
    }



    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAd($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAd() === $this) {
                $comment->setAd(null);
            }
        }

        return $this;
    }

    /**
     * @return \DateTimeInterface|null
     */
    public function getUpdateAt(): ?\DateTimeInterface
    {
        return $this->update_at;
    }

    /**
     * @param \DateTimeInterface|null $updated_at
     *
     */
    public function setUpdateAt(\DateTimeInterface $update_at): self
    {
        $this->update_at = $update_at;

        return $this;
    }

    
}

src/Controller/AdController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Entity\Image;
use App\Form\AnnonceType;
use App\Repository\AdRepository;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class AdController extends AbstractController
{
    /**
     * @Route("/ads", name="ads_index")
     */
    public function index(AdRepository $repo)
    {
        $ads = $repo->findAll();

        return $this->render('ad/index.html.twig', [
            'ads' => $ads
        ]);
    }


    /**
     * permet de créer une nouvelle annonce
     * 
     * @Route("/ads/new", name ="ads_create")
     *
     * 
     * @return Response
     */
    public function create(Request $request, ObjectManager $manager)
    {
        $ad = new Ad();

        $form = $this->createForm(AnnonceType::class, $ad);

        $form->handleRequest($request);

       
        if($form->isSubmitted() && $form->isValid()){

            //joindre l'utilisateur connecté à son annonce

            $ad->setAuthor($this-getUser());

            $manager->persist($ad);
            $manager->flush();

            $this->addFlash(
                'success',
                'Votre annonce' .$ad->getTitle(). 'a bien été envoyé'
            );

            return $this->redirectToRoute('ads_show', [
                'slug' => $ad->getSlug()
            ]);
  
        }

       
        return $this->render('ad/new.html.twig',[
            'form' => $form->createView()
        ]);

    }

    /**
     * permet de modifier une annonce
     * 
     * @Route("ads/{slug}/edit", name="ads_edit")
     * 
     * @Security("is_granted('ROLE_USER') and user === ad.getAuthor()",
     *  message="vous ne pouvez pas modifier une annonce qui n'est pas la votre")
     * 
     * @return Response
     */
    public function adsEdit(Ad $ad, Request $request, ObjectManager $manager){

        $form = $this->createForm(AnnonceType::class, $ad);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){

            $manager->persist($ad);
            $manager->flush();

            $this->addFlash(
                'success',
                'Votre annonce' .$ad->getTitle(). 'a bien été modifiée'
            );

            return $this->redirectToRoute('ads_show', [
                'slug' => $ad->getSlug()
            ]);
  
        }        

        return $this->render('ad/edit.html.twig',[
            'ad' => $ad,
            'form' => $form->createView()
        ]);

    }


    /**
     * permet d'afficher une annonce unique
     * 
     * @Route("/ads/{slug}", name="ads_show")
     * 
     * @return Response 
     */
    public function adShow(Ad $ad)
    {
        return $this->render('ad/show.html.twig', [
            'ad' => $ad
        ]);

    }

    /**
     * permet de supprimer une annonce
     * 
     * @Route("ads/{slug}/delete", name="ads_delete")
     *
     * @param Ad $ad
     * @param ObjectManager $manager
     * @return Response
     */
    public function delete(Ad $ad, ObjectManager $manager){
        $manager->remove($ad);
        $manager->flush();

        $this->addFlash(
            "success","l'annonce <strong>{$ad->getTitle()}</strong> a bien été supprimé"
        );

        return $this->redirectToRoute('ads_index');

    }


    
}

templates/ad/_ad.html.twig
 {% set url = path ('ads_show', {'slug': ad.slug}) %}

             <div class="col-md-4">
                <div class="card bg-light mb-3">
                    <div class="card-header text-center">
                     {{ ad.rooms }} chambres, <strong>{{ ad.price | number_format(2, ',', ' ')  }} &euro; / nuit</strong><br>

                     {% if ad.comments | length > 0 %}

                     {% include 'partials/rating.html.twig' with {'rating': ad.avgRatings} %}

                     {% else %}

                     <small>pas encore noté</small>

                     {% endif %}

                    </div>
                    <a href="{{ url }}">
                        <img src="" alt="image de l'appartement"
                        style="height: 200px; width: 100%; display: block">
                    </a>
                    
                    <div class="card-body">
                        <a href="{{ url }}">
                        <h4 class="card-title">{{ ad.title }}</h4>
                        </a>
                        
                        <p class="card-text">
                        {{ ad.introduction }}
                        </p>
                        <a href="{{ url }}" class="btn btn-primary float-right">En savoir plus</a>
                        {% if app.user and app.user == ad.author %}
                            <a href="{{ path('ads_edit', {'slug': ad.slug}) }}" 
                            class="btn btn-secondary">Modifier l'annonce</a>
                            
                        {% endif %}
                    </div>
                </div>

            
            </div>

templates/ad/_collection.html.twig
{% block _annonce_images_widget %}

    <p>Ajoutez vos images ici !</p>

    {{ form_widget(form) }}

    <input type="hidden" id="widgets-counter" value="0">

    <div class="form-group">
        <button type="button" id="add-image" class="btn btn-primary">
        <i class="fas fa-plus"></i>
        Ajouter une image</button>
    </div>

{% endblock %}

{% block _annonce_images_entry_row %}

    {{ form_widget(form) }}

{% endblock %}

{% block _annonce_images_entry_widget %}

    <div class="form-group" id="block_{{id}}">
        <div class="row">
            <div class="col-10">
                <div class="row">
                    <div class="col">{{ form_widget(form.url) }}</div>
                    <div class="col">{{ form_widget(form.caption) }}</div>
                </div>                
            </div>
                <div class="row">
                    <div class="col-2">
                        <button type="button" data-action="delete" data-target="#block_{{id}}" class="btn btn-danger">x</button>
                    </div>
                </div>
                

            
        </div>
        

    </div>

{% endblock %}

templates/ad/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %} 

Modification de : {{ad.title}} 

{% endblock %}

{% form_theme form 'ad/_collection.html.twig' %}

{% block body %}

<div class="container">
        <h1>Modifier l'annonce</h1>

        {{ form_start(form) }}

        {{ form_widget(form) }}

        <button type="submit" class="btn btn-primary">Enregistrer les Modification</button>

        {{ form_end(form) }}

</div>

{% endblock %}


{% block javascripts %}

<script src='/js/ad.js'></script>
        
{% endblock %}

templates/ad/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} Actualités {% endblock %}

{% block content %}

    <!-- Start Page Title Area -->
    <div class="page-title">
        <div class="d-table">
            <div class="d-table-cell">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12 col-md-12">
                            <h3>Actualités</h3>
                            <ul>
                                <li><a href="#">Accueil</a></li>
                                <li>/</li>
                                <li>Actualités</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Page Title Area -->

    <!-- Start Blog Area -->
    <section class="blog-area blog-style-two ptb-80">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-7 col-sm-7">
                    <div class="row">
                        {% for ad in ads %}
                            {% set url = path ('ads_show', {'slug': ad.slug}) %}

                            <div class="col-lg-6 col-md-12">
                                <div class="single-blog-post">
                                    <div class="thumb">
                                        <a href="{{ url }}">
                                        <img src="/assets/img/blog-img1.jpg" alt="blog-img">
                                        </a>
                                        <div class="blog-link">
                                            <a href="{{ url }}"><i class="fa fa-link"></i></a>
                                        </div>
                                        <div class="date">
                                            <span><br></span>
                                        </div>
                                    </div>
                                    <div class="post-content">
                                        <h3><a href="{{ url }}">{{ad.title}}</a></h3>
                                        <p>{{ ad.introduction }}</p>
                                    </div>
                                    <div class="post-meta">
                                        <ul>
                                            <li><a href="#"><i class="fa fa-user"></i> Admin</a></li>
                                            <li><a href="#"><i class="fa fa-heart-o"></i> 301</a></li>
                                            <li><a href="#"><i class="fa fa-comments-o"></i> 31</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            {% if app.user and app.user == ad.author %}
                                <a href="{{ path('ads_edit', {'slug': ad.slug}) }}"
                                   class="btn btn-secondary">Modifier l'annonce</a>

                            {% endif %}

                        {% endfor %}

                        <div class="col-lg-12 col-md-12">
                            <div class="pagination-area">
                                <nav aria-label="Page navigation">
                                    <ul class="pagination justify-content-center">
                                        <li class="page-item disabled">
                                            <a class="page-link" href="#" tabindex="-1"><i class="fa fa-angle-left"></i></a>
                                        </li>
                                        <li class="page-item active"><a class="page-link" href="#">1</a></li>
                                        <li class="page-item"><a class="page-link" href="#">2</a></li>
                                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                                        <li class="page-item">
                                            <a class="page-link" href="#"><i class="fa fa-angle-right"></i></a>
                                        </li>
                                    </ul>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-lg-4 col-md-5 col-sm-5">
                    <div class="side-bar mb-0">
                        <div class="side-bar-box search-box">
                            <form>
                                <input type="text" class="form-control" name="search" id="search-input" placeholder="Search">
                                <button type="submit"><i class="fa fa-search"></i></button>
                            </form>
                        </div>

                        <div class="side-bar-box categories-box">
                            <h3 class="title">Categories</h3>
                            <ul>
                                <li><a href="#"><i class="fa fa-angle-double-right"></i> News (10)</a></li>
                                <li><a href="#"><i class="fa fa-angle-double-right"></i> Legal News (15)</a></li>
                                <li><a href="#"><i class="fa fa-angle-double-right"></i> Events (09)</a></li>
                                <li><a href="#"><i class="fa fa-angle-double-right"></i> Resources (19)</a></li>
                                <li><a href="#"><i class="fa fa-angle-double-right"></i> Illegal News (13)</a></li>
                                <li><a href="#"><i class="fa fa-angle-double-right"></i> Legal Alerts (16)</a></li>
                                <li><a href="#"><i class="fa fa-angle-double-right"></i> Investigations (05)</a></li>
                            </ul>
                        </div>

                        <div class="side-bar-box tags-box">
                            <h3 class="title">Tags</h3>
                            <ul>
                                <li><a href="#">Resources</a></li>
                                <li><a href="#">Law</a></li>
                                <li><a href="#">Events</a></li>
                                <li><a href="#">Illegal</a></li>
                                <li><a href="#">Criminal</a></li>
                                <li><a href="#">Family</a></li>
                                <li><a href="#">News</a></li>
                                <li><a href="#">Legal</a></li>
                                <li><a href="#">Civil</a></li>
                                <li><a href="#">Divorce</a></li>
                                <li><a href="#">Investment</a></li>
                            </ul>
                        </div>

                        <div class="side-bar-box recent-post mb-0">
                            <h3 class="title">Recent Post</h3>
                            <div class="single-recent-post">
                                <div class="recent-post-img">
                                    <a href="#"><img src="assets/img/blog-img1.jpg" alt="blog-img"></a>
                                </div>
                                <div class="recent-post-content">
                                    <ul>
                                        <li><a href="#">By Admin</a></li>
                                        <li><a href="#"><i class="fa fa-calendar"></i> Jan 8, 2018</a></li>
                                    </ul>
                                    <h3><a href="#">Employment tribunal hears cases against National</a></h3>
                                </div>
                            </div>

                            <div class="single-recent-post">
                                <div class="recent-post-img">
                                    <a href="#"><img src="assets/img/blog-img2.jpg" alt="blog-img"></a>
                                </div>
                                <div class="recent-post-content">
                                    <ul>
                                        <li><a href="#">By Admin</a></li>
                                        <li><a href="#"><i class="fa fa-calendar"></i> Jan 8, 2018</a></li>
                                    </ul>
                                    <h3><a href="#">Employment tribunal hears cases against National</a></h3>
                                </div>
                            </div>

                            <div class="single-recent-post mb-0">
                                <div class="recent-post-img">
                                    <a href="#"><img src="assets/img/blog-img3.jpg" alt="blog-img"></a>
                                </div>
                                <div class="recent-post-content">
                                    <ul>
                                        <li><a href="#">By Admin</a></li>
                                        <li><a href="#"><i class="fa fa-calendar"></i> Jan 8, 2018</a></li>
                                    </ul>
                                    <h3><a href="#">Employment tribunal hears cases against National</a></h3>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End Blog Area -->

{% endblock %}